import {
  IconAssetType,
  IconCategory,
  IconDepartment,
  IconWarranty,
} from "~/app/components/ui/icons";
import { ConfigMeta } from "~/app/components/settings/configure-grid-types";

export const CONFIG_META: ConfigMeta[] = [
  {
    key: "category",
    label: "Category",
    icon: IconCategory,
    listTitle: "Categories",
    addTitle: "Add Category",
    editTitle: "Edit Category",
    nameLabel: "Category Name",
    namePlaceholder: "Enter category name",
    createEndpoint: "/api/categories",
    itemEndpoint: "/api/categories",
    successAddMessage: "Category added.",
    successEditMessage: "Category updated.",
    successInactiveMessage: "Category set inactive.",
    successActiveMessage: "Category set active.",
  },
  {
    key: "assetType",
    label: "Asset Type",
    icon: IconAssetType,
    listTitle: "Asset Types",
    addTitle: "Add Asset Type",
    editTitle: "Edit Asset Type",
    nameLabel: "Asset Type Name",
    namePlaceholder: "Enter asset type name",
    createEndpoint: "/api/asset-types",
    itemEndpoint: "/api/asset-types",
    successAddMessage: "Asset type added.",
    successEditMessage: "Asset type updated.",
    successInactiveMessage: "Asset type set inactive.",
    successActiveMessage: "Asset type set active.",
  },
  {
    key: "department",
    label: "Department",
    icon: IconDepartment,
    listTitle: "Departments",
    addTitle: "Add Department",
    editTitle: "Edit Department",
    nameLabel: "Department Name",
    namePlaceholder: "Enter department name",
    createEndpoint: "/api/departments",
    itemEndpoint: "/api/departments",
    successAddMessage: "Department added.",
    successEditMessage: "Department updated.",
    successInactiveMessage: "Department set inactive.",
    successActiveMessage: "Department set active.",
  },
  {
    key: "warranty",
    label: "Warranty",
    icon: IconWarranty,
    listTitle: "Warranty Periods",
    addTitle: "Add Warranty Period",
    editTitle: "Edit Warranty Period",
    nameLabel: "Warranty Name",
    namePlaceholder: 'Enter warranty name (ex: "3 months")',
    createEndpoint: "/api/warranty-periods",
    itemEndpoint: "/api/warranty-periods",
    successAddMessage: "Warranty period added.",
    successEditMessage: "Warranty period updated.",
    successInactiveMessage: "Warranty period set inactive.",
    successActiveMessage: "Warranty period set active.",
  },
];
